{% set name = "ldas-tools-utilities" %}
{% set version = "2.6.6" %}

# dependencies
{% set ldas_tools_cmake_version = "1.2.2" %}
{% set ldas_tools_diskcacheapi_version = "2.7.1" %}
{% set ldas_tools_frameapi_version = "2.6.5" %}
{% set ldas_tools_ldasgen_version = "2.7.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: fca735ba9977afd2137c4e5e9eaf43e4026448b20366e69eb78e0d97c8f7a07c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [unix]
    - make  # [unix]
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - ldas-tools-al
    - ldas-tools-diskcacheapi >={{ ldas_tools_diskcacheapi_version }}
    - ldas-tools-frameapi >={{ ldas_tools_frameapi_version }}
    - ldas-tools-framecpp
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}
  run:
    - ldas-tools-al
    - ldas-tools-diskcacheapi >={{ ldas_tools_diskcacheapi_version }}
    - ldas-tools-frameapi >={{ ldas_tools_frameapi_version }}
    - ldas-tools-framecpp
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}

test:
  commands:
    - ldas_create_rds --help

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools utility programs

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
