{% set name = "ldas-tools-utilities" %}
{% set version = "2.6.5" %}

# dependencies
{% set ldas_tools_cmake_version = "1.0.8" %}
{% set ldas_tools_diskcacheapi_version = "2.7.0" %}
{% set ldas_tools_frameapi_version = "2.6.4" %}
{% set ldas_tools_framecpp_version = "2.7.0" %}
{% set ldas_tools_ldasgen_version = "2.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 64eee9f92a111fdafdae1c248e747d1f1a11cc7e69656322f620d530351d57b5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - pkg-config  # [unix]
    - make  # [unix]
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - ldas-tools-al
    - ldas-tools-diskcacheapi {{ ldas_tools_diskcacheapi_version }}
    - ldas-tools-frameapi {{ ldas_tools_frameapi_version }}
    - ldas-tools-framecpp {{ ldas_tools_framecpp_version }}
    - ldas-tools-ldasgen {{ ldas_tools_ldasgen_version }}
  run:
    - ldas-tools-al
    - ldas-tools-diskcacheapi >={{ ldas_tools_diskcacheapi_version }}
    - ldas-tools-frameapi >={{ ldas_tools_frameapi_version }}
    - ldas-tools-framecpp >={{ ldas_tools_framecpp_version }}
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}

test:
  commands:
    - ldas_create_rds --help

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools utility programs

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
