{% set name = "ldas-tools-utilities" %}
{% set version = "2.7.1" %}

# dependencies
{% set ldas_tools_cmake_version = "1.2.3" %}
{% set ldas_tools_diskcacheapi_version = "2.7.2" %}
{% set ldas_tools_frameapi_version = "2.6.7" %}
{% set ldas_tools_ldasgen_version = "2.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 0586c015d7fb0dd869d01d6c7c40d6dcfababf605e208072b1df8abb27f81e7f

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - ldas-tools-al
    - ldas-tools-diskcacheapi >={{ ldas_tools_diskcacheapi_version }}
    - ldas-tools-frameapi >={{ ldas_tools_frameapi_version }}
    - ldas-tools-framecpp
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}
    - libboost-headers

test:
  commands:
    - ldas_create_rds --help

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools utility programs

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
