travis:
  secure:
    BINSTAR_TOKEN: TPX7ER6jraRwUmcalUt+1ZCyJW6EZuAnJlZADyICpyQDZPv4jjCoj1Aj3zZRQvWReoz0TXn+fnhkPtwmDvzIP32tEY0yKTv9hk9wcBtAOVy+JoAeONHVvtwBsTyoI1NwTbV9qnlNG+g6rYkIqqe+YsIlckiLMLzjLx2tx1bGX+xXILw45s0PcYpmNElHatmNoYepe6nAY/foOsIGOGtg6lutEhRshlcUfW/EKQ2QSDbmNJe6Rzo/Z3KGJcOdJm7eFSh9+uZCNMijbRXy33Z2CSmVG4R+dsN5fsJXnmjqE/5J1v4s/1LGi/xLMteSL7ygiH5jqJj4teuOEAhgehMHXeUm9JqUgCS2TNWPy2Gf0Wbq5sKbOoD7tuqAkq8V4Uv/6knOMJhHxiouRNVbCDt3wGpzVvYriu1iNUuj6xlfMhiO0YaY9/rYs1ka895ZMRlq3S210eND4aMo4eoaXs1UHZCfk8l9S2QSr3ND+X2CbMjWpPUq5Wi1AfAIXNuYfsJO748QGdu50+SDU/XE+Xp6xzERKGpC7rdLDrcCRk6XWSrYm7Lx1Hdhw8Oy2MVX+VDSjmeMNudtrXdC48Jfo8ejsCYPYuFtvXn0/Ccs7eUAYsaYQq8yqMedLaLH9htWovpxnL7lsEN5wFBXd2NtMuW34bcy4q7FiaofVd1snnag+J8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
